package rules;
import ftn.bsep.siemcenter.model.Log;
global java.util.List logsOutput;

rule "ERROR-log"
    when
        $log: Log( getLevel() == 'ERROR');
    then
    	logsOutput.add("ERROR has occured. Time: " + $log.getTimestamp() + " | Message: " + $log.getMessage() + "\n");
    	delete($log);
end 

rule "Special privileges - log on"
	when
	    $log: Log( getEventId() == '4672' && getLevel() == 'SUCCESS_AUDIT');
	then
		logsOutput.add("Special privileges -> LOG-ON  Time: " + $log.getTimestamp() + " | Message: " + $log.getMessage() + "\n");
		delete($log);
end 

rule "FAILURE 4625-login"
	when
	    $log: Log( getEventId() == '4625' && getLevel() == 'FAILURE_AUDIT' , $eventId: eventId );
	    Number(intValue >= 2) from accumulate(
        $log2: Log( this != $log, eventId == $eventId, this meets[5s] $log),count($log2))
	then
		logsOutput.add("Multiple failed login! Time: " + $log.getTimestamp() + "| Message: " + $log.getMessage() + "\n");
		delete($log);
end 
 

rule "LOGIN Mulitiple fail"
	when
	    $log: Log( getEventId() == '9999' && getLevel() == 'WARNING' , $eventId: eventId );
	    Number(intValue >= 2) from accumulate(
        $log2: Log( this != $log, eventId == $eventId, this meets[5s] $log),count($log2))
	then
		logsOutput.add("Multiple failed Application LOGIN! Time: " + $log.getTimestamp() + "| Message: " + $log.getMessage() + "\n");
		delete($log);
end 
 
rule "FAILURE-log"
	when
	    $log: Log( getLevel() == 'FAILURE' );
	then
		logsOutput.add("Failure log has occured. Time: " + $log.getTimestamp() + "| On machine: " + $log.getComputerName() + "Message: " + $log.getMessage() + "\n");
		delete($log);
end 
 
 
 

