package rules;
import ftn.bsep.siemcenter.model.Log;
global java.util.List logsOutput;


rule "LOG_ALWAYS-log"
    when
        $log: Log( getLevel() == 'LOG_ALWAYS' );
    then
    	logsOutput.clear();
    	logsOutput.add("Log_Always has occured. Time: " + $log.getTimestamp() + "| On machine: " + $log.getComputer_name() + "Message: " + $log.getMessage());
    	delete($log);
end 
 
rule "CRITICAL-log"
	when
	    $log: Log( getLevel() == 'CRITICAL' );
	then
		logsOutput.clear();
		logsOutput.add("Critical log has occured. Time: " + $log.getTimestamp() + "| On machine: " + $log.getComputer_name() + "Message: " + $log.getMessage());
		delete($log);
end 
 

rule "ERROR-log"
	when
	    $log: Log( getLevel() == 'ERROR' );
	then
		logsOutput.clear();
		logsOutput.add("Error log has occured. Time: " + $log.getTimestamp() + "| On machine: " + $log.getComputer_name() + "Message: " + $log.getMessage());
		delete($log);
end 
 
rule "WARNING-log"
	when
	    $log: Log( getLevel() == 'WARNING' );
	then
		logsOutput.clear();
		logsOutput.add("Warning log has occured. Time: " + $log.getTimestamp() + "| On machine: " + $log.getComputer_name() + "Message: " + $log.getMessage());
		delete($log);
end 
 
rule "INFORMATIONAL-log"
	when
	    $log: Log( getLevel() == 'INFORMATIONAL' );
	then
		logsOutput.clear();
		logsOutput.add("Informational log has occured. Time: " + $log.getTimestamp() + "| On machine: " + $log.getComputer_name() + "Message: " + $log.getMessage());
		delete($log);
end
 
rule "VERBOSE-log"
	when
	    $log: Log( getLevel() == 'VERBOSE' );
	then
		logsOutput.clear();
		logsOutput.add("Verbose log has occured. Time: " + $log.getTimestamp() + "| On machine: " + $log.getComputer_name() + "Message: " + $log.getMessage());
		delete($log);
end 
 

